# Generated by Django 4.0.1 on 2024-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dob',
            field=models.DateTimeField(default='1963-06-21'),
        ),
    ]
