# Generated by Django 4.0.1 on 2024-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
